algo: dqn
batch_size: 1024
buffer_size: 1000000
episode_length: 1024
epsilon: 1
epsilon_end: 0.05
epsilon_speed: 0.99998
evaluate_rate: 50
game_name: snake1v1
gamma: 0.9
hidden_size: 128
lr_a: 0.0001
lr_c: 0.0001
max_episodes: 80000
model_episode: 0
output_activation: softmax
run_redo: null
save_interval: 1000
seed_nn: 1
seed_np: 1
seed_random: 1
target_replace: 500
tau: 0.001
train_redo: false
